server:
  port: 9091
spring:
  application:
    name: employee-service
  main:
    allow-circular-references: true
    web-application-type: reactive
    #allow-bean-definition-overriding: true
  webflux:
    base-path: /employee-service
  jackson:
    default-property-inclusion: NON_NULL
  h2:
    console:
      enabled: true
      path: /h2-console 
  r2dbc:
    url: r2dbc:h2:mem:///employeedb?options=DB_CLOSE_DELAY=-1
    username: sa
    password:
#  datasource:
#    url: jdbc:h2:mem:studentdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 5
#      idle-timeout: 300000
#      max-lifetime: 1200000
#      auto-commit: true
redis:
  host: localhost
  port: 6379
  password: test
  connectionTimeoutInMin: 4
cache:
  type: caffeine
cache-duration:
  minutes: 1440
